export const OVERFLOW_HIDDEN = 'overflow:hidden'
export const OVERFLOW_X_HIDDEN = 'overflow-x:hidden'
export const HALYAVA_PROMO_CODE = 'HALYAVA'
export const BEVERAGE_PROMO_CODE = 'BEVERAGE'
export const DONER_PROMO_CODE = 'DONER'
export const SHIPPING_FEE = 2.5
export const PRODUCTS_BEGIN = 1
export const PRODUCTS_END = 17
export const BEVERAGE_BEGIN = 10
export const DONER_BEGIN = 4
export const DONER_END = 9
export const THIRD_ELEMENT = 2
export const BONUS_COEFFICIENT=0.05
export const DELETE = 'Backspace'
export const ZERO=0